name: Publish Python Package

on:
    workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel build twine

    - name: Read version
      id: version
      run: |
        echo "VERSION=$(cat .version)" >> $GITHUB_ENV

    - name: Configure Git for tagging
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create and push tag
      env:
        VERSION: ${{ env.VERSION }}
      run: |
        if git rev-parse "refs/tags/$VERSION" >/dev/null 2>&1; then
        echo "Tag $VERSION already exists, skipping tag creation."
        else
        git tag $VERSION
        git push origin $VERSION
        fi

    - name: Build distributions
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD

    - name: Show published version
      run: |
        echo "Published version: $VERSION"
